//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToyRobotWeb {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.FileUpload FileUploadInput;
		
		protected System.Web.UI.WebControls.Button ButtonUpload;
		
		protected System.Web.UI.WebControls.Button ButtonSubmit;
		
		protected System.Web.UI.WebControls.Label LabelInput;
		
		protected System.Web.UI.WebControls.Label LabelOutput;
		
		protected System.Web.UI.WebControls.TextBox TextBoxInput;
		
		protected System.Web.UI.WebControls.TextBox TextBoxOutput;

		protected System.Web.UI.WebControls.TextBox TextBoxAPIURL;
	}
}
